[package]
name = "ruyi_runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "lib"]

[dependencies]
inkwell = { workspace = true, optional = true }
thiserror.workspace = true
once_cell = "1.19"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["inkwell"]