// stdlib audit tool for Ruyi.
//
// Scans the standard library (stdlib/*.ry) for 8 documented modules
// (array, collections, map, set, string, math, time, json) and emits
// a Markdown report at docs/stdlib-audit-v0.5.5.md. The report lists
// every exported function / class / trait / constant in each module,
// flags bodies that look like stubs (contain only a TODO comment or
// an unimplemented!() marker), and explicitly notes modules whose
// source file does not yet exist.
//
// No dependencies: pure stdlib + std::fs / std::path reading.
//
// @author 罗泽罡
// @date 2026-07-10

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// One documented audit entry — corresponds to a row in the report.
#[derive(Debug)]
struct Module {
    /// Display name used in headings (e.g. `array`, `math`).
    name: &'static str,
    /// Module status: implemented (file present) or unimpl (file missing).
    status: Status,
    /// On-disk path of the source file the audit drew signatures from.
    /// `None` when the module file does not exist (math / time / json).
    source: Option<PathBuf>,
    /// Optional narrowing: when `source` covers multiple modules, this
    /// filters exported items by leading keyword (`ArrayIterator`,
    /// `Map`, `Set`, …). `None` means the whole file belongs to the
    /// module.
    filter: Option<&'static [&'static str]>,
}

#[derive(Debug, Clone, Copy)]
enum Status {
    Implemented,
    NotImplemented,
}

/// One exported item extracted from a `.ry` source file.
#[derive(Debug)]
struct Item {
    kind: &'static str, // `fn`, `class`, `trait`, `const`
    name: String,        // e.g. `ArrayIterator.new`
    signature: String,   // the source line, trimmed
    is_stub: bool,       // body is a TODO or unimplemented!() marker
}

fn main() {
    // Workspace root: tools/audit-stdlib/ → ../../
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("workspace root resolves to tools/audit-stdlib/../..");
    let stdlib_dir = workspace_root.join("stdlib");
    let docs_dir = workspace_root.join("docs");
    let report_path = docs_dir.join("stdlib-audit-v0.5.5.md");

    let modules = [
        Module {
            name: "array",
            status: Status::Implemented,
            source: Some(stdlib_dir.join("collections.ry")),
            filter: Some(&["ArrayIterator", "ArrayOps"]),
        },
        Module {
            name: "collections",
            status: Status::Implemented,
            source: Some(stdlib_dir.join("collections.ry")),
            filter: Some(&["Iterator"]),
        },
        Module {
            name: "map",
            status: Status::Implemented,
            source: Some(stdlib_dir.join("collections.ry")),
            filter: Some(&["Map", "MapIterator"]),
        },
        Module {
            name: "set",
            status: Status::Implemented,
            source: Some(stdlib_dir.join("collections.ry")),
            filter: Some(&["Set", "SetIterator"]),
        },
        Module {
            name: "string",
            status: Status::Implemented,
            source: Some(stdlib_dir.join("string.ry")),
            filter: None,
        },
        Module {
            name: "math",
            status: Status::NotImplemented,
            source: None,
            filter: None,
        },
        Module {
            name: "time",
            status: Status::NotImplemented,
            source: None,
            filter: None,
        },
        Module {
            name: "json",
            status: Status::NotImplemented,
            source: None,
            filter: None,
        },
    ];

    let mut report = String::new();
    write_report_header(&mut report);
    for module in &modules {
        audit_module(&mut report, module);
    }
    write_report_footer(&mut report);

    fs::create_dir_all(&docs_dir).expect("create docs/");
    fs::write(&report_path, &report).expect("write report");
    println!("Wrote {}", report_path.display());
}

fn write_report_header(buf: &mut String) {
    let _ = writeln!(
        buf,
        "# Ruyi Standard Library Audit (v0.5.5)\n"
    );
    let _ = writeln!(
        buf,
        "Generated by `tools/audit-stdlib`. Lists exported function, class, \
         trait, and const declarations for 8 documented modules, and flags \
         bodies whose only content is a `TODO` comment or an \
         `unimplemented!()` marker (i.e. stubs that need real implementation).\n"
    );
    let _ = writeln!(
        buf,
        "Modules listed as **未实装 (not implemented)** have no \
         corresponding source file under `stdlib/` yet; the audit does NOT \
         add those files — implementation is out of scope for v0.5.5.\n"
    );
    let _ = writeln!(buf, "## Summary\n");
    let _ = writeln!(
        buf,
        "| Module     | Status        | Source                          |"
    );
    let _ = writeln!(
        buf,
        "|------------|---------------|---------------------------------|"
    );
    let _ = writeln!(
        buf,
        "| array      | implemented   | `stdlib/collections.ry`         |"
    );
    let _ = writeln!(
        buf,
        "| collections| implemented   | `stdlib/collections.ry`         |"
    );
    let _ = writeln!(
        buf,
        "| map        | implemented   | `stdlib/collections.ry`         |"
    );
    let _ = writeln!(
        buf,
        "| set        | implemented   | `stdlib/collections.ry`         |"
    );
    let _ = writeln!(
        buf,
        "| string     | implemented   | `stdlib/string.ry`              |"
    );
    let _ = writeln!(
        buf,
        "| math       | **未实装**    | `stdlib/math.ry` (does not exist) |"
    );
    let _ = writeln!(
        buf,
        "| time       | **未实装**    | `stdlib/time.ry` (does not exist) |"
    );
    let _ = writeln!(
        buf,
        "| json       | **未实装**    | `stdlib/json.ry` (does not exist) |\n"
    );
}

fn write_report_footer(buf: &mut String) {
    let _ = writeln!(
        buf,
        "## Methodology\n\n\
         1. For implemented modules, the tool reads the source file and \
            extracts every `export fn`, `export class`, `export trait`, and \
            `export const` line (filtered by class name prefix when a single \
            file backs multiple modules).\n\
         2. For each function body, the tool scans lines between the \
            signature line and the matching closing brace for `TODO` comments \
            or `unimplemented!()` markers. If those markers are the only \
            content, the entry is flagged `STUB`.\n\
         3. For unimplemented modules, the tool reports the missing file \
            path and notes that implementation is out of scope for v0.5.5.\n\n\
         Re-run with `cargo run -p audit-stdlib` from the workspace root to \
         regenerate this file."
    );
}

fn audit_module(buf: &mut String, module: &Module) {
    let status_label = match module.status {
        Status::Implemented => "implemented",
        Status::NotImplemented => "未实装 (not implemented)",
    };
    let _ = writeln!(buf, "## {}\n", module.name);
    let _ = writeln!(buf, "**Status:** {}\n", status_label);

    let Some(source_path) = &module.source else {
        let _ = writeln!(
            buf,
            "No source file exists at `stdlib/{}.ry`. This module is part of \
             the documented v0.5.5 surface but has not been implemented yet. \
             Implementation is intentionally deferred — see Batch 1.3 audit \
             (T-1.3.3) and the v0.5.5 roadmap.\n",
            module.name
        );
        return;
    };

    let source = match fs::read_to_string(source_path) {
        Ok(s) => s,
        Err(e) => {
            let _ = writeln!(
                buf,
                "_Could not read `{}`: {}_\n",
                source_path.display(),
                e
            );
            return;
        }
    };

    let items = extract_items(&source, module.filter);
    let stubs: Vec<&Item> = items.iter().filter(|i| i.is_stub).collect();
    let total = items.len();

    let _ = writeln!(
        buf,
        "Source: `{}` — {} exported item{}\n",
        source_path
            .strip_prefix(
                source_path
                    .ancestors()
                    .nth(2)
                    .unwrap_or(source_path),
            )
            .unwrap_or(source_path)
            .display(),
        total,
        if total == 1 { "" } else { "s" }
    );

    if items.is_empty() {
        let _ = writeln!(buf, "_No exported items matched the filter._\n");
        return;
    }

    let _ = writeln!(buf, "| Kind   | Name | Signature |");
    let _ = writeln!(buf, "|--------|------|-----------|");
    for item in &items {
        let stub_marker = if item.is_stub { " ⚠ STUB" } else { "" };
        // Escape pipe characters so Markdown table parsing survives.
        let sig = item.signature.replace('|', "\\|");
        let _ = writeln!(
            buf,
            "| {:<6} | `{}`{} | `{}` |",
            item.kind,
            item.name,
            stub_marker,
            sig
        );
    }
    let _ = writeln!(buf);
    if stubs.is_empty() {
        let _ = writeln!(
            buf,
            "_No stubs detected — every body has at least one non-trivial \
             statement._\n"
        );
    } else {
        let _ = writeln!(
            buf,
            "**Stubs ({} of {}):** the following bodies are pure TODO / \
             `unimplemented!()` markers and need real implementation:\n",
            stubs.len(),
            total
        );
        for stub in &stubs {
            let _ = writeln!(buf, "- `{}` — {}", stub.name, stub.signature);
        }
        let _ = writeln!(buf);
    }
}

/// Walk a `.ry` source string, extract every exported declaration that
/// matches the optional filter (class-name prefix), and pair each function
/// with a "is this a stub?" verdict.
///
/// The walker tracks brace depth to determine which class / trait / impl
/// a method belongs to. Trait method declarations (e.g. `fn name(): T;`
/// without a body) are handled by detecting the trailing `;` instead of
/// looking for a matching `{ ... }` block.
fn extract_items(source: &str, filter: Option<&'static [&'static str]>) -> Vec<Item> {
    let mut items: Vec<Item> = Vec::new();
    let lines: Vec<&str> = source.lines().collect();

    // Stack of class / trait / impl contexts so nested `impl` blocks
    // (e.g. `impl ArrayOps for Array<T>`) report fn names as
    // `ArrayOps.fnName`, not the enclosing class name.
    let mut context: Vec<String> = Vec::new();
    // Brace depth at the top of each context push (so we know when to pop).
    let mut depth_stack: Vec<usize> = Vec::new();
    let mut brace_depth: usize = 0;

    let mut idx = 0;
    while idx < lines.len() {
        let raw = lines[idx];
        let line = raw.trim();

        // Pop context when the matching closing brace is consumed.
        while let Some(&top_depth) = depth_stack.last() {
            if brace_depth < top_depth {
                context.pop();
                depth_stack.pop();
            } else {
                break;
            }
        }

        if let Some(name) = parse_class_header(line) {
            let qualifies = matches_filter(&name, filter);
            if qualifies {
                items.push(Item {
                    kind: "class",
                    name: name.clone(),
                    signature: line.to_string(),
                    is_stub: false,
                });
            }
            context.push(name);
            brace_depth += count_open_braces(line);
            depth_stack.push(brace_depth);
            idx += 1;
            continue;
        }
        if let Some(name) = parse_trait_header(line) {
            let qualifies = matches_filter(&name, filter);
            if qualifies {
                items.push(Item {
                    kind: "trait",
                    name: name.clone(),
                    signature: line.to_string(),
                    is_stub: false,
                });
            }
            context.push(name);
            brace_depth += count_open_braces(line);
            depth_stack.push(brace_depth);
            idx += 1;
            continue;
        }
        if let Some(name) = parse_impl_header(line) {
            // `impl ArrayOps for Array<T>` — report fn names under the
            // trait being implemented (`ArrayOps`) rather than the
            // concrete type.
            context.push(name);
            brace_depth += count_open_braces(line);
            depth_stack.push(brace_depth);
            idx += 1;
            continue;
        }

        // Pure-close lines update depth before any other processing.
        let opens = count_open_braces(line);
        let closes = count_close_braces(line);

        let in_context = !context.is_empty();
        let visible = match (filter, context.last()) {
            (None, _) => true,
            (Some(_), Some(name)) => matches_filter(name, filter),
            (Some(_), None) => false,
        };

        if !visible {
            // Skip past a method body if we are inside a filtered-out
            // class so we don't leak its fn names into another module.
            if in_context && line.starts_with("fn ") {
                let end = find_fn_end(&lines, idx);
                idx = end + 1;
                brace_depth = brace_depth.saturating_sub(closes);
                brace_depth += opens;
                continue;
            }
            brace_depth = brace_depth.saturating_sub(closes);
            brace_depth += opens;
            idx += 1;
            continue;
        }

        let (kind, sig) = match parse_export_or_method(line, in_context) {
            Some(parsed) => parsed,
            None => {
                brace_depth = brace_depth.saturating_sub(closes);
                brace_depth += opens;
                idx += 1;
                continue;
            }
        };

        let qualified_name = if kind == "fn" {
            match context.last() {
                Some(class) => format!("{}.{}", class, sig.name),
                None => sig.name.clone(),
            }
        } else {
            sig.name.clone()
        };

        // Determine stub-ness for fn bodies. Trait declarations (`fn x(): T;`)
        // have no body — treat them as non-stub but emit a single line
        // signature (the declaration itself).
        let is_stub = if kind == "fn" {
            if is_trait_declaration(line) {
                false
            } else {
                let end = find_fn_end(&lines, idx);
                let body = &lines[idx..=end.min(lines.len().saturating_sub(1))];
                is_stub_body(body)
            }
        } else {
            false
        };

        items.push(Item {
            kind,
            name: qualified_name,
            signature: sig.signature,
            is_stub,
        });

        // Skip past the function body so the next iteration starts after
        // its matching closing brace. Trait declarations end at `;` so
        // `find_fn_end` returns the same line (no body to skip).
        let end = find_fn_end(&lines, idx);
        idx = end + 1;
        brace_depth = brace_depth.saturating_sub(closes);
        brace_depth += opens;
    }
    items
}

/// Count `{` characters on a line (ignoring those inside string literals
/// is intentionally out of scope — Ruyi `.ry` source files do not contain
/// `{` in string literals at this point).
fn count_open_braces(line: &str) -> usize {
    line.chars().filter(|&c| c == '{').count()
}

/// Count `}` characters on a line.
fn count_close_braces(line: &str) -> usize {
    line.chars().filter(|&c| c == '}').count()
}

/// `impl<T> ArrayOps<T> for Array<T> {` — return `Some("ArrayOps")` so the
/// enclosing fn names are reported as `ArrayOps.fnName`.
fn parse_impl_header(line: &str) -> Option<String> {
    let line = line.trim();
    let after = line.strip_prefix("impl")?;
    // Skip optional `<...>` generics on the impl block.
    let after = skip_generics(after);
    let name = take_ident(after);
    if name.is_empty() {
        return None;
    }
    Some(name.to_string())
}

/// Skip `<...>` if present, returning the rest of the string.
fn skip_generics(s: &str) -> &str {
    let s = s.trim_start();
    if let Some(rest) = s.strip_prefix('<') {
        let mut depth = 1;
        for (idx, ch) in rest.char_indices() {
            match ch {
                '<' => depth += 1,
                '>' => {
                    depth -= 1;
                    if depth == 0 {
                        return rest[idx + 1..].trim_start();
                    }
                }
                _ => {}
            }
        }
    }
    s
}

/// A trait method declaration looks like `fn name(...): ReturnType;` —
/// it ends with `;`, never `{`. We use this to skip to the next line
/// instead of looking for a matching closing brace.
fn is_trait_declaration(line: &str) -> bool {
    let trimmed = line.trim();
    trimmed.starts_with("fn ") && trimmed.ends_with(';') && !trimmed.contains('{')
}

/// Find the end of a function body. Returns:
/// - the same index for a `;`-terminated trait declaration (no body to
///   skip — caller advances by one line as usual),
/// - the line containing the matching `}` for a normal function body.
fn find_fn_end(lines: &[&str], start: usize) -> usize {
    let signature = lines[start].trim();
    if is_trait_declaration(signature) {
        return start;
    }
    find_body_end(lines, start)
}

/// Decide whether `name` matches any entry in the optional filter list.
/// `None` filter means "no filtering" — everything matches.
fn matches_filter(name: &str, filter: Option<&[&str]>) -> bool {
    match filter {
        None => true,
        Some(prefixes) => prefixes.iter().any(|p| {
            name == *p
                || name.starts_with(&format!("{}<", p))
                || name.starts_with(&format!("{},", p))
        }),
    }
}

struct ParsedExport {
    name: String,
    signature: String,
}

/// Recognize `export fn name(...)`, `export class Name`, `export trait Name`,
/// `export const NAME`. When `in_class` is true, also accept bare `fn name(...)`
/// lines (methods inside a class / trait body do not repeat `export`).
fn parse_export_or_method(
    line: &str,
    in_class: bool,
) -> Option<(&'static str, ParsedExport)> {
    let line = line.trim();
    if let Some(rest) = line.strip_prefix("export ") {
        return parse_export_after_export(rest, line);
    }
    if in_class {
        if let Some(rest) = line.strip_prefix("fn ") {
            let name = extract_fn_name(rest);
            return Some((
                "fn",
                ParsedExport {
                    name,
                    signature: line.to_string(),
                },
            ));
        }
    }
    None
}

fn parse_export_after_export(
    rest: &str,
    original_line: &str,
) -> Option<(&'static str, ParsedExport)> {
    if let Some(after) = rest.strip_prefix("fn ") {
        let name = extract_fn_name(after);
        return Some((
            "fn",
            ParsedExport {
                name,
                signature: original_line.to_string(),
            },
        ));
    }
    if let Some(after) = rest.strip_prefix("class ") {
        let name = take_ident(after).to_string();
        return Some((
            "class",
            ParsedExport {
                name,
                signature: original_line.to_string(),
            },
        ));
    }
    if let Some(after) = rest.strip_prefix("trait ") {
        let name = take_ident(after).to_string();
        return Some((
            "trait",
            ParsedExport {
                name,
                signature: original_line.to_string(),
            },
        ));
    }
    if let Some(after) = rest.strip_prefix("const ") {
        let name = take_ident(after).to_string();
        return Some((
            "const",
            ParsedExport {
                name,
                signature: original_line.to_string(),
            },
        ));
    }
    None
}

fn parse_class_header(line: &str) -> Option<String> {
    let line = line.trim();
    let after = line.strip_prefix("export class ")?;
    Some(take_ident(after).to_string())
}

fn parse_trait_header(line: &str) -> Option<String> {
    let line = line.trim();
    let after = line.strip_prefix("export trait ")?;
    Some(take_ident(after).to_string())
}

/// `fn new(arr: Array<T>)` → `new`.
fn extract_fn_name(after_fn_kw: &str) -> String {
    // Methods are `fn name(...)`; the name is the first identifier.
    take_ident(after_fn_kw).to_string()
}

/// Take characters that are valid in a Ruyi identifier (letter / digit /
/// underscore, must not start with digit).
fn take_ident(s: &str) -> &str {
    let bytes = s.as_bytes();
    let mut end = 0;
    while end < bytes.len() {
        let b = bytes[end];
        let is_first = end == 0;
        let ok = b.is_ascii_alphabetic() || b == b'_' || (!is_first && b.is_ascii_digit());
        if !ok {
            break;
        }
        end += 1;
    }
    &s[..end]
}

/// Walk forward from the signature line looking for the matching closing
/// brace at brace depth 0. Returns the index of the closing brace (or the
/// last line of the file if the body never closes).
fn find_body_end(lines: &[&str], start: usize) -> usize {
    let mut depth: i32 = 0;
    let mut seen_open = false;
    for (offset, raw) in lines.iter().enumerate().skip(start) {
        for ch in raw.chars() {
            match ch {
                '{' => {
                    depth += 1;
                    seen_open = true;
                }
                '}' => {
                    depth -= 1;
                    if seen_open && depth == 0 {
                        return offset;
                    }
                }
                _ => {}
            }
        }
    }
    lines.len().saturating_sub(1)
}

/// Decide whether a function body is a stub. A body is a stub iff its
/// non-comment, non-whitespace lines reduce to zero meaningful statements
/// after stripping the signature line, closing brace, `return
/// unimplemented!()`, and `// TODO` comments.
fn is_stub_body(body: &[&str]) -> bool {
    let mut has_marker = false;
    for raw in body {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        // Skip the signature line (e.g. `fn x() {`) and the trailing brace.
        if line.starts_with("fn ") || line == "}" {
            continue;
        }
        if line.starts_with("//") {
            // Pure comment line — a stub if the comment mentions TODO/FIXME.
            let upper = line.to_ascii_uppercase();
            if upper.contains("TODO") || upper.contains("FIXME") {
                has_marker = true;
            }
            continue;
        }
        let stripped = line
            .trim_start_matches("return")
            .trim()
            .trim_end_matches(';')
            .trim();
        if stripped.starts_with("unimplemented!") || stripped.starts_with("todo!") {
            has_marker = true;
            continue;
        }
        return false;
    }
    has_marker
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_export_recognises_fn_class_trait_const() {
        assert!(parse_export_or_method("export fn join(a: int, b: int): int {", false).is_some());
        assert!(parse_export_or_method("export class Map<K, V> {", false).is_some());
        assert!(parse_export_or_method("export trait Iterator<T> {", false).is_some());
        assert!(parse_export_or_method("export const PI: float = 3.14;", false).is_some());
        assert!(parse_export_or_method("let x = 1;", false).is_none());
        assert!(parse_export_or_method("    return foo;", false).is_none());
    }

    #[test]
    fn take_ident_handles_generic_names() {
        assert_eq!(take_ident("ArrayIterator<T>"), "ArrayIterator");
        assert_eq!(take_ident("PI: float"), "PI");
        assert_eq!(take_ident("Map<K, V>"), "Map");
    }

    #[test]
    fn is_stub_body_flags_only_todo_comment() {
        let body = ["fn x() {", "    // TODO: implement", "}"];
        assert!(is_stub_body(&body));
    }

    #[test]
    fn is_stub_body_flags_unimplemented_call() {
        let body = ["fn x() {", "    return unimplemented!();", "}"];
        assert!(is_stub_body(&body));
    }

    #[test]
    fn is_stub_body_rejects_real_implementation() {
        let body = ["fn x() {", "    return __builtin_foo(self);", "}"];
        assert!(!is_stub_body(&body));
    }

    #[test]
    fn extract_items_filters_by_prefix() {
        let src = "\
export class ArrayIterator<T> {
    fn new(arr: Array<T>) {
        self._array = arr;
    }
}
export class Map<K, V> {
    fn new() {
        self._data = 0;
    }
}
";
        let items = extract_items(src, Some(&["ArrayIterator"]));
        let names: Vec<&str> = items.iter().map(|i| i.name.as_str()).collect();
        assert!(names.iter().any(|n| n.contains("ArrayIterator.new")));
        assert!(!names.iter().any(|n| n.contains("Map")));
    }
}